version: '3'
services:
  retail:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:bike
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - h2
  h2:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
